// 일본 맛집 데이터 (실제 유명 맛집 리서치 기반)
// hours: 대표 영업시간 (변동될 수 있어 방문 전 확인 권장)
// map: 구글맵 검색어 / rating·reviews: 실제 구글 지도 별점·리뷰 수 (수집 시점 기준)
// 나고야는 구글 별점 4.0 이상 기준으로 재선정 (총 51곳)
window.RESTAURANT_DATA = {
  cities: [
    { id: "tokyo",   name: "도쿄",   jp: "東京",   emoji: "🗼" },
    { id: "osaka",   name: "오사카", jp: "大阪",   emoji: "🏯" },
    { id: "sapporo", name: "삿포로", jp: "札幌",   emoji: "❄️" },
    { id: "fukuoka", name: "후쿠오카", jp: "福岡", emoji: "🍜" },
    { id: "nagoya",  name: "나고야", jp: "名古屋", emoji: "🏭" },
    { id: "kyoto",   name: "교토",   jp: "京都",   emoji: "⛩️" }
  ],
  places: {
    tokyo: [
      { name: "이치란 시부야", jp: "一蘭 渋谷店", type: "음식점", category: "ramen",
        hours: "24시간 영업", area: "시부야", map: "一蘭 渋谷店 東京",
        menu: ["톤코츠 라멘", "카에다마(면 추가)", "매운 비법 다레"] },
      { name: "라멘 나기", jp: "ラーメン凪", type: "음식점", category: "ramen",
        hours: "화–일 11:30–15:00, 18:00–23:30", area: "시부야 골든가이", map: "ラーメン凪 新宿ゴールデン街店",
        menu: ["니보시 라멘", "돼지고기 차슈", "특제 츠케멘"] },
      { name: "긴자 하치고", jp: "銀座 八五", type: "음식점", category: "ramen",
        hours: "화–일 11:00 ~ 수프 소진 시 마감", area: "긴자", map: "銀座 八五 東京",
        menu: ["츄카소바(시오)", "츄카소바(쇼유)", "와자토 계란"] },
      { name: "모테나시 쿠로키", jp: "饗 くろ喜", type: "음식점", category: "ramen",
        hours: "월–토 11:00–15:00, 18:00–20:00", area: "아사쿠사바시", map: "饗 くろ喜 浅草橋",
        menu: ["쇼유 라멘", "시오 소바", "계절 한정 소바"] },
      { name: "츠나하치 신주쿠 본점", jp: "つな八 新宿総本店", type: "음식점", category: "tempura",
        hours: "매일 11:00–22:00", area: "신주쿠", map: "つな八 新宿総本店",
        menu: ["튀김 정식", "튀김 덮밥", "제철 카운터 튀김"] },
      { name: "다이코쿠야 텐푸라 아사쿠사", jp: "大黒家天麩羅 浅草", type: "음식점", category: "tempura",
        hours: "매일 11:10–20:30", area: "아사쿠사", map: "大黒家天麩羅 浅草本店",
        menu: ["에비 텐동", "카키아게동", "참기름 튀김"] },
      { name: "톤카츠 마이센 아오야마 본점", jp: "とんかつ まい泉 青山本店", type: "음식점", category: "tonkatsu",
        hours: "매일 11:00–20:45", area: "아오야마", map: "とんかつ まい泉 青山本店",
        menu: ["히레카츠", "로스카츠", "카츠 샌드"] },
      { name: "부타구미 니시아자부", jp: "豚組 西麻布", type: "음식점", category: "tonkatsu",
        hours: "11:30–14:00, 18:00–22:00", area: "니시아자부", map: "豚組 西麻布 東京",
        menu: ["명품 돼지 로스카츠", "히레카츠", "품종별 돈카츠"] },
      { name: "스시잔마이 츠키지 본점", jp: "すしざんまい 築地本店", type: "음식점", category: "sushi",
        hours: "24시간 영업", area: "츠키지", map: "すしざんまい 築地本店",
        menu: ["혼마구로 3종", "오마카세 니기리", "제철 스시"] },
      { name: "이즈에이 우에노 본점", jp: "伊豆栄 上野本店", type: "음식점", category: "unagi",
        hours: "매일 11:00–21:00", area: "우에노", map: "伊豆栄 上野本店",
        menu: ["우나주(장어덮밥)", "장어 시라야키", "장어 회석"] },
      { name: "사보루", jp: "さぼうる", type: "카페", category: "cafe",
        hours: "월–토 11:00–23:00 (방문 전 확인)", area: "진보초", map: "さぼうる 神保町",
        menu: ["나폴리탄 스파게티", "핸드드립 커피", "크림소다"] },
      { name: "킷사 유", jp: "喫茶YOU", type: "카페", category: "cafe",
        hours: "매일 11:00–17:00 (방문 전 확인)", area: "긴자", map: "喫茶YOU 銀座",
        menu: ["폭신 오므라이스", "푸딩", "블렌드 커피"] },
      { name: "카야바 커피", jp: "カヤバ珈琲", type: "카페", category: "cafe",
        hours: "화–일 08:00–18:00", area: "야나카", map: "カヤバ珈琲 谷中",
        menu: ["타마고 샌드", "루시안(커피+코코아)", "안버터 토스트"] }
    ],
    osaka: [
      { name: "혼케 오오타코", jp: "本家 大たこ", type: "음식점", category: "takoyaki",
        hours: "매일 09:00–23:00", area: "도톤보리", map: "本家 大たこ 道頓堀",
        menu: ["원조 타코야키", "큰 문어 타코야키", "소스+가츠오부시"] },
      { name: "타코야키 도라쿠 와나카", jp: "たこ焼道楽 わなか", type: "음식점", category: "takoyaki",
        hours: "월–금 10:00–23:00, 토·일 09:00–23:00", area: "난바 센니치마에", map: "たこ焼道楽 わなか 千日前本店",
        menu: ["타코야키 8개 세트", "네기마요 타코야키", "타코센"] },
      { name: "치보 도톤보리", jp: "千房 道頓堀", type: "음식점", category: "okonomiyaki",
        hours: "매일 11:00–23:00 (L.O. 22:00)", area: "도톤보리", map: "千房 道頓堀ビル店",
        menu: ["도톤보리 야키(믹스)", "모던야키", "네기야키"] },
      { name: "원조 쿠시카츠 다루마 신세카이", jp: "元祖串かつ だるま 新世界", type: "음식점", category: "kushikatsu",
        hours: "매일 11:00–22:30", area: "신세카이", map: "元祖串かつ だるま 新世界総本店",
        menu: ["쿠시카츠 모둠", "소고기 쿠시카츠", "도테야키"] },
      { name: "규카츠 모토무라 난바", jp: "牛かつ もと村 なんば店", type: "음식점", category: "gyukatsu",
        hours: "매일 11:00–22:00", area: "난바", map: "牛かつ もと村 なんば店",
        menu: ["규카츠 정식", "돌판 셀프 굽기", "믹스 규카츠"] },
      { name: "멘야 조로쿠", jp: "麺屋 丈六", type: "음식점", category: "ramen",
        hours: "11:00–15:00, 18:00–22:00 (부정기 휴무)", area: "난바", map: "麺屋 丈六 大阪",
        menu: ["츄카소바", "니보시 소바", "차슈동"] },
      { name: "간소 부치기리즈시 우오신 난바", jp: "元祖ぶっちぎり寿司 魚心 難波", type: "음식점", category: "sushi",
        hours: "매일 11:00–23:00", area: "난바", map: "魚心 難波店 大阪",
        menu: ["점보 니기리", "모둠 스시", "제철 생선"] },
      { name: "551 호라이 난바 본점", jp: "551蓬莱 本店", type: "음식점", category: "chuka",
        hours: "매일 10:00–22:00", area: "난바", map: "551蓬莱 本店 難波",
        menu: ["부타망(고기만두)", "야키교자", "슈마이"] },
      { name: "릴로 커피 킷사", jp: "Lilo Coffee Kissa", type: "카페", category: "cafe",
        hours: "매일 12:00–20:00 (방문 전 확인)", area: "미나미호리에", map: "Lilo Coffee Kissa 大阪",
        menu: ["스페셜티 핸드드립", "사이폰 커피", "푸딩 아라모드"] },
      { name: "블루보틀 우메다 차야마치", jp: "Blue Bottle Coffee 梅田茶屋町", type: "카페", category: "cafe",
        hours: "매일 08:00–20:00", area: "우메다", map: "ブルーボトルコーヒー 梅田茶屋町",
        menu: ["싱글 오리진 드립", "카페라떼", "벨기에 와플"] },
      { name: "아메리칸", jp: "アメリカン", type: "카페", category: "cafe",
        hours: "매일 09:00–23:00 (방문 전 확인)", area: "도톤보리", map: "アメリカン 道頓堀 喫茶",
        menu: ["핫케이크", "프루츠 파르페", "레트로 크림소다"] }
    ],
    sapporo: [
      { name: "멘야 사이미", jp: "麺屋 彩未", type: "음식점", category: "ramen",
        hours: "11:00–15:00, 16:00–21:00 (계절 변동)", area: "미소노", map: "麺屋 彩未 札幌",
        menu: ["미소 라멘", "차슈멘", "생강 볶음 토핑"] },
      { name: "스미레 본점", jp: "すみれ 本店", type: "음식점", category: "ramen",
        hours: "11:00–15:00, 16:00–21:00", area: "나카노시마", map: "すみれ 札幌 本店",
        menu: ["스미레 미소 라멘", "쇼유 라멘", "시오 라멘"] },
      { name: "아지노 산페이", jp: "味の三平", type: "음식점", category: "ramen",
        hours: "화–일 11:00–18:30 (방문 전 확인)", area: "오도리", map: "味の三平 札幌",
        menu: ["원조 미소 라멘", "차슈멘", "삿포로 미소"] },
      { name: "오쿠시바 상점", jp: "奥芝商店", type: "음식점", category: "soupcurry",
        hours: "11:00–15:00, 17:00–21:00 (방문 전 확인)", area: "삿포로 도심", map: "奥芝商店 札幌",
        menu: ["치킨 야채 수프카레", "새우 육수 수프카레", "매운맛 선택"] },
      { name: "수프카레 스아게", jp: "スープカレー Suage", type: "음식점", category: "soupcurry",
        hours: "월·목 11:30–20:00, 화·수·금 11:30–20:30, 토·일 11:00–20:30", area: "스스키노", map: "スープカレー Suage+ すすきの本店",
        menu: ["라벤더 포크 수프카레", "치킨 수프카레", "구운 야채"] },
      { name: "수프카레 가라쿠", jp: "スープカレー GARAKU", type: "음식점", category: "soupcurry",
        hours: "11:30–15:30, 17:00–20:30 (방문 전 확인)", area: "타누키코지", map: "スープカレー GARAKU 札幌",
        menu: ["닭다리 수프카레", "치즈 토핑", "16종 스파이스 수프"] },
      { name: "삿포로 카니혼케 역앞 본점", jp: "札幌かに本家 駅前本店", type: "음식점", category: "crab",
        hours: "매일 11:30–22:00", area: "삿포로역", map: "札幌かに本家 駅前本店",
        menu: ["대게 코스", "게 샤부샤부", "게살 솥밥"] },
      { name: "돈부리차야 니조시장", jp: "どんぶり茶屋 二条市場店", type: "음식점", category: "kaisendon",
        hours: "매일 07:30–17:30", area: "니조시장", map: "どんぶり茶屋 二条市場店",
        menu: ["성게·연어알 덮밥", "모둠 카이센동", "게살 덮밥"] },
      { name: "징기스칸 다루마 본점", jp: "成吉思汗 だるま 本店", type: "음식점", category: "jingisukan",
        hours: "매일 17:00–23:00", area: "스스키노", map: "成吉思汗 だるま 本店 札幌",
        menu: ["양고기 징기스칸", "생 양고기", "특제 다레"] },
      { name: "모리히코 본점", jp: "森彦 本店", type: "카페", category: "cafe",
        hours: "매일 10:00–20:00 (방문 전 확인)", area: "마루야마", map: "森彦 本店 札幌",
        menu: ["모리노 시즈쿠 블렌드", "핸드드립 커피", "치즈케이크"] },
      { name: "파르페 커피 주류 사토우", jp: "パフェ、珈琲、酒、佐藤", type: "카페", category: "cafe",
        hours: "매일 18:00–24:00 (방문 전 확인)", area: "스스키노", map: "パフェ 珈琲 酒 佐藤 すすきの",
        menu: ["시메 파르페", "계절 파르페", "커피"] }
    ],
    fukuoka: [
      { name: "잇푸도 다이묘 본점", jp: "一風堂 大名本店", type: "음식점", category: "ramen",
        hours: "매일 11:00–22:00", area: "다이묘", map: "一風堂 大名本店 福岡",
        menu: ["시로마루 모토아지", "아카마루 신아지", "가에다마"] },
      { name: "하카타 잇코샤 총본점", jp: "博多 一幸舎 総本店", type: "음식점", category: "ramen",
        hours: "월–토 11:00–23:30, 일 11:00–21:00", area: "하카타", map: "博多 一幸舎 総本店",
        menu: ["톤코츠 라멘", "거품 톤코츠 스프", "차슈멘"] },
      { name: "하카타 라멘 신신 텐진", jp: "博多らーめん Shin-Shin 天神本店", type: "음식점", category: "ramen",
        hours: "매일 11:00–다음날 03:00 (방문 전 확인)", area: "텐진", map: "博多らーめん Shin-Shin 天神本店",
        menu: ["하카타 라멘", "명란 밥", "야키교자"] },
      { name: "하카타 모츠나베 오야마", jp: "博多もつ鍋 おおやま", type: "음식점", category: "motsunabe",
        hours: "17:00–24:00 (방문 전 확인)", area: "하카타", map: "博多もつ鍋 おおやま 本店",
        menu: ["미소 모츠나베", "쇼유 모츠나베", "챤폰 사리"] },
      { name: "하카타 모츠나베 쇼라쿠", jp: "博多もつ鍋 笑楽", type: "음식점", category: "motsunabe",
        hours: "16:00–23:00 (L.O. 22:30)", area: "하카타역 3분", map: "博多もつ鍋 笑楽 本店",
        menu: ["쇼유 모츠나베", "미소 모츠나베", "명란 계란말이"] },
      { name: "미즈타키 하나미도리", jp: "水炊き 博多 華味鳥", type: "음식점", category: "mizutaki",
        hours: "매일 11:30–15:00, 17:00–23:00", area: "나카스", map: "水炊き 博多 華味鳥 中洲本店",
        menu: ["미즈타키(닭 전골)", "토리사시", "닭죽 마무리"] },
      { name: "하카타 토리카와 다이진", jp: "博多 とりかわ 大臣", type: "음식점", category: "yakitori",
        hours: "매일 17:00–24:00 (방문 전 확인)", area: "하루요시", map: "博多 とりかわ 大臣 春吉本店",
        menu: ["토리카와(닭목살 꼬치)", "모둠 야키토리", "명란 계란말이"] },
      { name: "원조 하카타 멘타이주", jp: "元祖博多めんたい重", type: "음식점", category: "mentaiko",
        hours: "매일 07:00–22:30", area: "스미요시", map: "元祖博多めんたい重",
        menu: ["멘타이주(명란 덮밥)", "명란 계란말이", "명란 파스타"] },
      { name: "인바 우동", jp: "因幡うどん", type: "음식점", category: "udon",
        hours: "매일 10:00–19:00 (방문 전 확인)", area: "하카타", map: "因幡うどん 博多デイトス店",
        menu: ["고보텐 우동", "마루텐 우동", "가케 우동"] },
      { name: "REC 커피 야쿠인", jp: "REC COFFEE 薬院駅前店", type: "카페", category: "cafe",
        hours: "매일 08:00–24:00 (방문 전 확인)", area: "야쿠인", map: "REC COFFEE 薬院駅前店",
        menu: ["스페셜티 라떼", "핸드드립", "치즈 타르트"] }
    ],
    nagoya: [
      { name: "아츠타 호라이켄 본점", jp: "あつた蓬莱軒 本店", type: "음식점", category: "unagi",
        rating: 4.5, reviews: 7624, price: "￥4,000~5,000", area: "아츠타 신궁", map: "あつた蓬莱軒 本店 名古屋" },
      { name: "히츠마부시 하나오카", jp: "ひつまぶし花岡", type: "음식점", category: "unagi",
        rating: 4.7, reviews: 2089, price: "￥4,000~5,000", area: "사카에", map: "ひつまぶし花岡 名古屋 栄" },
      { name: "마루야 본점 JR나고야역점", jp: "まるや本店 JR名古屋駅店", type: "음식점", category: "unagi",
        rating: 4.3, reviews: 2220, price: "￥4,000~6,000", area: "나고야역", map: "まるや本店 JR名古屋駅店" },
      { name: "히루다케 우나기야 사카에 본점", jp: "昼だけうなぎ屋 栄本店", type: "음식점", category: "unagi",
        rating: 4.5, reviews: 4438, price: "￥2,000~3,000", area: "사카에", map: "昼だけうなぎ屋 栄本店 名古屋" },
      { name: "우나기노 시로무라 이즈미 본점", jp: "うなぎのしろむら 泉本店", type: "음식점", category: "unagi",
        rating: 4.5, reviews: 1729, price: "￥4,000~5,000", area: "이즈미", map: "うなぎのしろむら 泉本店 名古屋" },
      { name: "야바톤 야바초 본점", jp: "矢場とん 矢場町本店", type: "음식점", category: "misokatsu",
        rating: 4.1, reviews: 6300, price: "￥1,000~2,000", area: "오스/야바초", map: "矢場とん 矢場町本店" },
      { name: "쿠로부타야 라무치", jp: "黒豚屋 らむちぃ", type: "음식점", category: "misokatsu",
        rating: 4.3, reviews: 2152, price: "￥1,000~2,000", area: "사카에", map: "黒豚屋 らむちぃ 栄 名古屋" },
      { name: "미카와야", jp: "三河屋", type: "음식점", category: "misokatsu",
        rating: 4.2, reviews: 1305, price: "￥1,000~2,000", area: "묘젠초", map: "三河屋 名古屋 味噌カツ 明前町" },
      { name: "테바사키 무츠미 본점", jp: "手羽先むつみ 本店", type: "음식점", category: "tebasaki",
        rating: 4.7, reviews: 731, price: "￥2,000~3,000", area: "사카에", map: "手羽先むつみ 本店 名古屋" },
      { name: "나고야메시 식당 마루하치", jp: "名古屋めし食堂 丸八", type: "음식점", category: "nagoyameshi",
        rating: 4.0, reviews: 757, price: "￥1,000~2,000", area: "나고야역(루센트타워)", map: "名古屋めし食堂 丸八 ルーセントタワー" },
      { name: "미야 키시멘 진구점", jp: "宮きしめん 神宮店", type: "음식점", category: "kishimen",
        rating: 4.2, reviews: 1675, price: "￥~1,000", area: "아츠타 신궁", map: "宮きしめん 神宮店" },
      { name: "키시멘 요시다 에스카점", jp: "きしめんよしだ エスカ店", type: "음식점", category: "kishimen",
        rating: 4.0, reviews: 895, price: "￥1,000~2,000", area: "나고야역 에스카", map: "きしめんよしだ エスカ店 名古屋" },
      { name: "오쿠테 야마모토야", jp: "大久手山本屋", type: "음식점", category: "misonikomi",
        rating: 4.3, reviews: 844, price: "￥1,000~2,000", area: "오쿠테", map: "大久手山本屋 名古屋" },
      { name: "미소니코미 타카라", jp: "味噌にこみ たから", type: "음식점", category: "misonikomi",
        rating: 4.3, reviews: 648, price: "￥1,000~2,000", area: "오스", map: "味噌にこみ たから 大須 名古屋" },
      { name: "미소니코미노 카쿠마루", jp: "みそ煮込みの角丸", type: "음식점", category: "misonikomi",
        rating: 4.2, reviews: 808, price: "￥1,000~2,000", area: "이즈미", map: "みそ煮込みの角丸 名古屋" },
      { name: "소레 앙카케스파 총본점", jp: "そーれ あんかけスパ総本店", type: "음식점", category: "ankake",
        rating: 4.1, reviews: 1187, price: "￥~1,000", area: "사카에", map: "そーれ あんかけスパ総本店 名古屋" },
      { name: "앙카케스파 전문점 나폴리", jp: "あんかけスパ専門店 ナポリ", type: "음식점", category: "ankake",
        rating: 4.1, reviews: 469, price: "￥1,000~2,000", area: "아이오이초", map: "あんかけスパ専門店 ナポリ 名古屋" },
      { name: "카라미소 라멘 후쿠로우 본점", jp: "からみそラーメンふくろう 本店", type: "음식점", category: "ramen",
        rating: 4.3, reviews: 1029, price: "￥1,000~2,000", area: "츠지초", map: "からみそラーメンふくろう 本店 名古屋" },
      { name: "도쿄 미소 스타일 이케다", jp: "Tokyo miso style IKEDA", type: "음식점", category: "ramen",
        rating: 4.2, reviews: 501, price: "￥1,000~2,000", area: "하타에도리", map: "Tokyo miso style IKEDA 名古屋" },
      { name: "긴노쿠라 나고야 본점", jp: "銀のくら 名古屋本店", type: "음식점", category: "ramen",
        rating: 4.1, reviews: 739, price: "￥1,000~2,000", area: "이즈미", map: "銀のくら 名古屋本店 味噌ラーメン" },
      { name: "우동 니시키", jp: "うどん 錦", type: "음식점", category: "curryudon",
        rating: 4.1, reviews: 1077, price: "￥~1,000", area: "니시키", map: "うどん 錦 名古屋 カレーうどん" },
      { name: "카레우동 모미지", jp: "カレーうどん椛", type: "음식점", category: "curryudon",
        rating: 4.5, reviews: 238, price: "￥1,000~2,000", area: "우치데", map: "カレーうどん椛 名古屋" },
      { name: "유덴테이 타쿠미", jp: "有伝亭 匠", type: "음식점", category: "curryudon",
        rating: 4.4, reviews: 166, price: "￥~1,000", area: "사카에", map: "有伝亭 匠 名古屋 うどん" },
      { name: "스시노 미도리", jp: "寿司の美登利", type: "음식점", category: "sushi",
        rating: 4.3, reviews: 1758, price: "￥3,000~4,000", area: "나고야역", map: "寿司の美登利 名古屋 名駅" },
      { name: "스시 노보루", jp: "すし昇", type: "음식점", category: "sushi",
        rating: 4.8, reviews: 86, price: "￥10,000~", area: "마루노우치", map: "すし昇 丸の内 名古屋" },
      { name: "오스즈시", jp: "大須鮨", type: "음식점", category: "sushi",
        rating: 4.9, reviews: 208, price: "￥2,000~6,000", area: "오스", map: "大須鮨 名古屋" },
      { name: "니쿠노 요이치 나고야역 본점", jp: "お米と焼肉 肉のよいち 名駅本店", type: "음식점", category: "yakiniku",
        rating: 4.4, reviews: 3673, price: "￥1,000~5,000", area: "나고야역", map: "お米と焼肉 肉のよいち 名駅本店" },
      { name: "나고야역 야키니쿠 후시미야 히다규 별저", jp: "名駅焼肉 伏見屋 飛騨牛 別邸", type: "음식점", category: "yakiniku",
        rating: 4.9, reviews: 3606, price: "￥4,000~10,000", area: "나고야역", map: "名駅焼肉 伏見屋 飛騨牛 別邸" },
      { name: "모우모우테이", jp: "もうもう亭", type: "음식점", category: "yakiniku",
        rating: 4.5, reviews: 1247, price: "￥2,000~3,000", area: "사카에", map: "もうもう亭 栄 名古屋 焼肉" },
      { name: "텐푸라 카키아게 미츠무라", jp: "天ぷら かき揚げ 光村", type: "음식점", category: "tempura",
        rating: 4.3, reviews: 1744, price: "", area: "시미즈", map: "天ぷら かき揚げ 光村 名古屋" },
      { name: "텐푸라 나카에", jp: "天麩羅なか江", type: "음식점", category: "tempura",
        rating: 4.1, reviews: 84, price: "￥1,000~2,000", area: "사카에", map: "天麩羅なか江 名古屋 栄" },
      { name: "텐푸라토 와인 코지마 본점", jp: "天ぷらとワイン小島 本店", type: "음식점", category: "tempura",
        rating: 4.0, reviews: 778, price: "￥1,000~5,000", area: "나고야역", map: "天ぷらとワイン小島 本店 名古屋" },
      { name: "히네리자구치하이 테루마에 나고야역앞", jp: "大衆酒泉テルマエ 名古屋駅前", type: "음식점", category: "izakaya",
        rating: 4.5, reviews: 3730, price: "￥2,000~3,000", area: "나고야역", map: "大衆酒泉テルマエ 名古屋駅前 ひねり蛇口ハイ" },
      { name: "로바타야키 이부시긴 명역서구점", jp: "炉端焼き 燻銀 名駅西口店", type: "음식점", category: "izakaya",
        rating: 4.8, reviews: 1894, price: "￥4,000~6,000", area: "나고야역 서구", map: "炉端焼き 燻銀 名駅西口店" },
      { name: "니모노 나고야역점", jp: "にもの 名古屋駅店", type: "음식점", category: "izakaya",
        rating: 4.6, reviews: 598, price: "￥3,000~4,000", area: "나고야역", map: "にもの 名古屋駅店" },
      { name: "키센테이 미드랜드스퀘어점", jp: "喜扇亭 名古屋ミッドランドスクエア店", type: "음식점", category: "teppanyaki",
        rating: 4.6, reviews: 127, price: "￥10,000~", area: "나고야역", map: "喜扇亭 名古屋ミッドランドスクエア店" },
      { name: "텟판 이즈미 산카이", jp: "鉄板Izumi〜さんかい〜", type: "음식점", category: "teppanyaki",
        rating: 4.6, reviews: 62, price: "￥10,000~", area: "이즈미", map: "鉄板Izumi さんかい 名古屋" },
      { name: "텟판야키 나고테이", jp: "鉄板焼 那古亭", type: "음식점", category: "teppanyaki",
        rating: 4.3, reviews: 235, price: "￥10,000~", area: "나고야역(마리오트)", map: "鉄板焼 那古亭 名古屋マリオット" },
      { name: "이치니치주 모닝 킷사 모닝", jp: "一日中モーニング 喫茶モーニング", type: "카페", category: "cafe",
        rating: 4.4, reviews: 696, price: "￥~1,000", area: "노리타케", map: "一日中モーニング 喫茶モーニング 名古屋" },
      { name: "부쵸 커피", jp: "BUCYO COFFEE", type: "카페", category: "cafe",
        rating: 4.3, reviews: 1955, price: "￥1,000~2,000", area: "나고야역 남쪽", map: "BUCYO COFFEE 名古屋 名駅南" },
      { name: "Q.O.L. 커피", jp: "Q.O.L. COFFEE", type: "카페", category: "cafe",
        rating: 4.4, reviews: 646, price: "￥~1,000", area: "마루노우치", map: "Q.O.L. COFFEE 名古屋 丸の内" },
      { name: "선데이 풀러 카페", jp: "SUNDAY FULLER CAFE", type: "카페", category: "cafe",
        rating: 4.4, reviews: 459, price: "￥1,000~2,000", area: "나고야역 남쪽", map: "SUNDAY FULLER CAFE 名古屋" },
      { name: "카페 톨란드", jp: "CAFE TOLAND", type: "카페", category: "cafe",
        rating: 4.5, reviews: 697, price: "￥1,000~2,000", area: "오스", map: "CAFE TOLAND 大須 名古屋" },
      { name: "카페 드 시엘", jp: "カフェ ド シエル", type: "카페", category: "cafe",
        rating: 4.2, reviews: 517, price: "￥1,000~2,000", area: "나고야역(타카시마야 51F)", map: "カフェ ド シエル JR名古屋タカシマヤ" },
      { name: "츠바키사료", jp: "椿茶寮 tsubakisaryo", type: "카페", category: "dessert",
        rating: 4.8, reviews: 60, price: "￥2,000~3,000", area: "이즈미", map: "椿茶寮 名古屋 泉" },
      { name: "파르페 드 뤼엘", jp: "parfait de ruelle", type: "카페", category: "dessert",
        rating: 4.1, reviews: 81, price: "￥1,000~2,000", area: "오스", map: "parfait de ruelle 大須 名古屋" },
      { name: "피에르 마르콜리니 나고야", jp: "ピエール マルコリーニ 名古屋", type: "카페", category: "dessert",
        rating: 4.3, reviews: 696, price: "￥1,000~2,000", area: "나고야역(미드랜드)", map: "ピエール マルコリーニ 名古屋 ミッドランドスクエア" },
      { name: "수리프", jp: "スーリープー", type: "카페", category: "bakery",
        rating: 4.3, reviews: 1183, price: "￥1,000~2,000", area: "치요다", map: "スーリープー 名古屋 千代田" },
      { name: "팡도루 마루타케", jp: "パンドールまるたけ", type: "카페", category: "bakery",
        rating: 4.3, reviews: 303, price: "", area: "신사카에", map: "パンドールまるたけ 名古屋 新栄" },
      { name: "알버트 커피 로스터스", jp: "Albert Coffee Roasters", type: "카페", category: "cafe",
        rating: 4.8, reviews: 81, price: "", area: "가미오타이", map: "Albert Coffee Roasters 名古屋 上小田井" },
      { name: "슈러브 커피 나고야", jp: "SHRUB COFFEE NAGOYA", type: "카페", category: "cafe",
        rating: 4.6, reviews: 102, price: "￥1,000~2,000", area: "나고야역 남쪽(나야바시)", map: "SHRUB COFFEE NAGOYA 納屋橋" }
    ],
    kyoto: [
      { name: "오멘 긴카쿠지 본점", jp: "おめん 銀閣寺本店", type: "음식점", category: "udon",
        hours: "11:00–21:00 (부정기 휴무)", area: "긴카쿠지", map: "おめん 銀閣寺本店",
        menu: ["오멘(제철 야채 츠케우동)", "튀김 우동", "볶음 우동"] },
      { name: "총본가 카와미치야", jp: "総本家 河道屋", type: "음식점", category: "soba",
        hours: "11:00–20:00 (목요일 휴무)", area: "가라스마", map: "総本家 河道屋 京都",
        menu: ["호레이 소바(냄비)", "니신 소바", "자루 소바"] },
      { name: "혼케 오와리야 본점", jp: "本家尾張屋 本店", type: "음식점", category: "soba",
        hours: "매일 11:00–15:30 (방문 전 확인)", area: "니시키/가라스마", map: "本家尾張屋 本店 京都",
        menu: ["호카이 소바", "니신 소바", "소바 가이세키"] },
      { name: "총본가 니신소바 마츠바", jp: "総本家にしんそば松葉 本店", type: "음식점", category: "soba",
        hours: "매일 10:30–21:00 (수요일 휴무)", area: "시조 미나미자", map: "総本家にしんそば松葉 本店 京都",
        menu: ["니신 소바(원조)", "덴푸라 소바", "가케 소바"] },
      { name: "본가 다이이치아사히 타카바시", jp: "本家 第一旭 たかばし本店", type: "음식점", category: "ramen",
        hours: "매일 06:00–다음날 01:00 (방문 전 확인)", area: "교토역", map: "本家 第一旭 たかばし本店",
        menu: ["특제 라멘(쇼유)", "차슈멘", "야키메시"] },
      { name: "텐카잇핀 이치조지 총본점", jp: "天下一品 総本店 一乗寺", type: "음식점", category: "ramen",
        hours: "매일 11:00–다음날 01:00 (방문 전 확인)", area: "이치조지", map: "天下一品 総本店 一乗寺",
        menu: ["콧테리 라멘", "앗사리 라멘", "당수육 세트"] },
      { name: "교토 카츠규 시조카라스마", jp: "京都勝牛 四条烏丸", type: "음식점", category: "gyukatsu",
        hours: "매일 11:00–22:00", area: "시조카라스마", map: "京都勝牛 四条烏丸店",
        menu: ["규카츠 젠", "규카츠 카레", "돌판 굽기"] },
      { name: "효테이", jp: "瓢亭", type: "음식점", category: "kaiseki",
        hours: "11:00–19:30 (예약 권장, 부정기 휴무)", area: "난젠지", map: "瓢亭 京都",
        menu: ["아침 카이세키", "쇼카도 벤토", "효테이 반숙란"] },
      { name: "이노다 커피 본점", jp: "イノダコーヒ 本店", type: "카페", category: "cafe",
        hours: "매일 07:00–18:00", area: "산조 사카이마치", map: "イノダコーヒ 本店 京都",
        menu: ["아라비아의 진주 블렌드", "교토식 모닝", "치즈케이크"] },
      { name: "스마트 커피", jp: "スマート珈琲店", type: "카페", category: "cafe",
        hours: "매일 08:00–19:00 (2층 런치 11:00–14:30)", area: "테라마치", map: "スマート珈琲店 京都",
        menu: ["에그 샌드위치", "핫케이크", "핸드드립 커피"] },
      { name: "로쿠요샤 커피점", jp: "六曜社珈琲店", type: "카페", category: "cafe",
        hours: "매일 08:00–22:00 (방문 전 확인)", area: "가와라마치 산조", map: "六曜社珈琲店 京都",
        menu: ["자가배전 블렌드", "수제 도넛", "아이스 커피"] },
      { name: "사료 츠지리 기온 본점", jp: "茶寮都路里 祇園本店", type: "카페", category: "cafe",
        hours: "매일 10:00–19:00 (방문 전 확인)", area: "기온", map: "茶寮都路里 祇園本店",
        menu: ["말차 파르페", "말차 빙수", "말차 젠자이"] }
    ]
  }
};
